### ISSUE TITLE
Clean/Trim won't save to shapefile

### ISSUE THREAD

**Issue by cratcliff** [CSIRO-Precision-Agriculture/pyprecag#43]
While trying to runing the clean/trim tool, I received the following error message.
```
2021-08-06 12:11:38.615 pyprecag   CRITICAL  single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "C:/Users/30193641/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\gui\cleanTrimPoints_wizard.py", line 1063, in accept
    iterative=self.chkIterate.isChecked())
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pyprecag\processing.py", line 645, in clean_trim_points
    out_removed_shapefile, overwrite=True)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pyprecag\describe.py", line 249, in save_geopandas_tofile
    fldProp = get_column_properties(inputGeoDataFrame)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pyprecag\describe.py", line 310, in get_column_properties
    fldtype = type(dataframe.iloc[0][col]).__name__
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pandas\core\indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pandas\core\indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\pandas\core\indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

The input parameters I am using are
```
Parameters:---------------------------------------
    Layer:                                  	yldstdmois_13pc with 5190 selected features
    Process Field:                          	YldStdMois
    Thinning Distance:                      1.0m
    Remove Zeros:                           	True
    Standard Devs to Use:                3.0
    Trim Iteratively:                       	True
    Output Projected Coordinate System:     	EPSG:28354 - GDA94 / MGA zone 54
    Saved CSV File:                         	yldstdmois_13pc_z54_rules_trim_it.csv
    Saved Points:                           	yldstdmois_13pc_z54_rules_trim_it.shp
    Saved Removed Points:                   	yldstdmois_13pc_z54_rules_trim_it_removedpts.shp
```

**Comment by cratcliff** [comment]
This is due to the removed points shapefile being empty - ie no features are removed during filtering. 

This will be fixed in the next release coming soon.
